# It contains all the configs required in the project

artifacts:
  ARTIFACTS_DIR: artifacts
  PREPARED_DATA: prepared
  TRAIN_DATA: train.tsv
  TEST_DATA: test.tsv
  FEATURIZED_DATA: features
  FEATURIZED_DATA_TRAIN: train.pk1
  FEATURIZED_DATA_TEST: test.pk1

  MODEL_DIR: model
  MODEL_NAME: model.pk1

matrics:
  SCORES: scores.json

plots:
  PRC: prc.json
  ROC: roc.json

source_data:
  data_dir: data
  data_file: data.xml